version: '2.0'
services:
    influxdb:
        image: "influxdb:1.8-alpine"
        container_name: honeypot_influxdb
        environment:
            - INFLUXDB_DB=honeypot
            - INFLUXDB_ADMIN_USER=honey
            - INFLUXDB_ADMIN_PASSWORD=honey
            - INFLUXDB_HTTP_FLUX_ENABLED=true
            - INFLUXDB_HTTP_LOG_ENABLED=false
        ports:
            - "8086:8086"
