version: '3.0'
services:
    webserver:
        build:
            context: ..
            dockerfile: docker/go.docker
        entrypoint: ["go", "run", "cmd/webserver/webserver.go"]
        ports:
            - "8080:8080"
    listener:
        build:
            context: ..
            dockerfile: docker/go.docker
        entrypoint: ["go", "run", "cmd/listener/listener.go"]
        ports:
            - "27017:27017"
            - "3306:3306"
            - "5432:5432"
            - "7474:7474"
            - "9200:9200"
    processor:
        build:
            context: ..
            dockerfile: docker/go.docker
        entrypoint: ["go", "run", "cmd/processor/processor.go"]
    storer:
        build:
            context: ..
            dockerfile: docker/go.docker
        entrypoint: ["go", "run", "cmd/storer/storer.go"]
