version: '3.0'
services:
    chronograf:
        image: "chronograf:1.8-alpine"
        container_name: honeypot_chronograf
        environment:
            - INFLUXDB_URL=http://influxdb:8086
            - INFLUXDB_HTTP_FLUX_ENABLED=true
        ports:
            - "8888:8888"
