version: '3.0'
services:
    # Services
    listener:
        container_name: honeypot-listener
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/listener"]
        depends_on:
            - rabbitmq
            - influxdb
        ports:
            - "27017:27017"
            - "3306:3306"
            - "5432:5432"
            - "7474:7474"
            - "9200:9200"
    processor:
        container_name: honeypot-processor
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/processor"]
        depends_on:
            - rabbitmq
            - influxdb
    storer:
        container_name: honeypot-storer
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/storer"]
        depends_on:
            - rabbitmq
            - influxdb
    webserver:
        container_name: honeypot-webserver
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/webserver"]
        depends_on:
            - rabbitmq
            - influxdb
        ports:
            - "8100:8100"
        depends_on:
            - influxdb

    # Influxdb
    influxdb:
        image: "influxdb:1.8-alpine"
        container_name: honeypot-influxdb
        environment:
            - INFLUXDB_DB=honeypot
            - INFLUXDB_ADMIN_USER=honey
            - INFLUXDB_ADMIN_PASSWORD=honey
            - INFLUXDB_HTTP_FLUX_ENABLED=true
            - INFLUXDB_HTTP_LOG_ENABLED=false
        ports:
            - "8086:8086"

    # Rabbitmq
    rabbitmq:
        image: "rabbitmq:3.8-alpine"
        container_name: honeypot-rabbitmq
        hostname: honeypot-rabbitmq
        ports:
            - "5672:5672"
