version: '3.0'
services:
    # Services
    listener:
        container_name: honeypot-listener
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/listener"]
        depends_on:
            - rabbitmq
            - postgres
        ports:
            - "27017:27017"
            - "3306:3306"
            - "5432:5432"
            - "7474:7474"
            - "9200:9200"
    processor:
        container_name: honeypot-processor
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/processor"]
        depends_on:
            - rabbitmq
            - postgres
    storer:
        container_name: honeypot-storer
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/storer"]
        depends_on:
            - rabbitmq
            - postgres
    webserver:
        container_name: honeypot-webserver
        build:
            context: ..
            dockerfile: Dockerfile
        entrypoint: ["/app/bin/webserver"]
        depends_on:
            - rabbitmq
            - postgres
        ports:
            - "8100:8100"
        depends_on:
            - postgres

    # Postgres and Rabbitmq
    postgres:
        container_name: honeypot-postgres
        image: postgres:9.6
        environment:
          - POSTGRES_DB=honeypot_db
          - POSTGRES_USER=honeypot_user
          - POSTGRES_PASSWORD=honeypot_pass
          - PGDATA=/data
        volumes:
          - pgdata:/data

    # Rabbitmq
    rabbitmq:
        image: "rabbitmq:3.8-alpine"
        container_name: honeypot-rabbitmq
        hostname: honeypot-rabbitmq


volumes:
  pgdata:
